
        <div class="container container-pad" id="property-listings">
            
            <div class="row">
              <div class="col-md-12">
                <h1>Million Dollar Home Listings</h1>
                <p>A snippet I recently used to display homes for a local brokerage.  Focused more on images when accessed through mobile</p>
              </div>
            </div>
           <div class="row"> 
           <?php foreach ($places as $place) : ?>   
           
                
                <div class="col-sm-6"> 

                    <!-- Begin Listing: 609 W GRAVERS LN-->
                    <div class="brdr bgc-fff pad-10 box-shad btm-mrg-20 property-listing">
                        <div class="media">
                            <a class="pull-left" href="#" target="_parent">
                            <img alt="image" class="img-responsive" src="http://images.prd.mris.com/image/V2/1/Yu59d899Ocpyr_RnF0-8qNJX1oYibjwp9TiLy-bZvU9vRJ2iC1zSQgFwW-fTCs6tVkKrj99s7FFm5Ygwl88xIA.jpg"></a>

                            <div class="clearfix visible-sm"></div>

                            <div class="media-body fnt-smaller">
                                <a href="#" target="_parent"></a>

                                <h4 class="media-heading">
                                  <a href="#" target="_parent">$1,975,000 <small class="pull-right"><?php echo $this->escapeHTML($place->title)?></small></a></h4>


                                <ul class="list-inline mrg-0 btm-mrg-10 clr-535353">
                                    <li>4,820 SqFt</li>

                                    <li style="list-style: none">|</li>

                                    <li>5 Beds</li>

                                    <li style="list-style: none">|</li>

                                    <li>5 Baths</li>
                                </ul>

                                <p class="hidden-xs">Situated between fairmount
                                park and the prestigious philadelphia cricket
                                club, this beautiful 2+ acre property is truly
                                ...</p><span class="fnt-smaller fnt-lighter fnt-arial">Courtesy of HS Fox & Roach-Chestnut Hill
                                Evergreen</span>
                            </div>
                        </div>
                    </div><!-- End Listing-->
                  </div>
                <?php endforeach; ?>
            </div><!-- End row -->
        </div><!-- End container -->
